cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'go'
brew 'openssl'
brew 'unrar'
brew 'yarn'
brew 'ruby-build'
brew 'rbenv'
brew 'postgresql'
brew 'node'
brew 'youtube-dl'

cask 'tunnelbear'
cask 'handbrake'
cask 'max'
cask 'steam'
cask 'visual-studio-code'
cask 'paparazzi'
cask 'tunnelbear'
cask 'slack'
cask 'visual-studio'
cask 'docker'
cask 'kitematic'
cask 'postman'
cask 'genymotion'
cask 'spotify'
cask 'google-chrome'
cask 'laplock'
cask 'android-file-transfer'
cask 'vlc'
cask 'intellij-idea-ce'